# Generated by Django 5.2 on 2025-05-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_listings_comments_bids"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
